/*
=========================================================
Problem: Find Missing Elements

Difficulty: Easy

Category:
- Arrays

Pattern:
- Sorting

Approach:
- Sort the array in ascending order.
- Initialize a variable with the smallest element.
- Traverse the sorted array.
- For every gap between two consecutive elements,
  add all missing numbers to the answer list.
- Return the list of missing elements.

Time Complexity: O(n log n)
Space Complexity: O(1) (excluding the output list)

Key Learning:
- Sorting helps identify gaps between consecutive elements.
- Missing numbers can be generated by checking the
  difference between adjacent elements.

Optimization:
- If the array is already sorted, the time complexity
  becomes O(n).
- Without sorting, a HashSet can be used for O(n) lookup,
  but additional space is required.

Common Mistake:
- Forgetting to handle gaps larger than one.
- Not considering duplicate elements if they are allowed.

=========================================================
*/
package array;
import java.util.ArrayList;
class Solution {

    public List<Integer> findMissingElements(int[] nums) {

        Arrays.sort(nums);

        List<Integer> missingElements = new ArrayList<>();

        int expected = nums[0];

        for (int num : nums) {

            while (expected < num) {
                missingElements.add(expected);
                expected++;
            }

            expected = num + 1;
        }

        return missingElements;
    }
}